return {
  require 'plugins.autopairs',
  require 'plugins.comment',
  require 'plugins.git',
  require 'plugins.hardtime',
  require 'plugins.lsp',
  require 'plugins.markdown',
  require 'plugins.mini',
  require 'plugins.oil',
  require 'plugins.smear-cursor',
  require 'plugins.telescope',
  require 'plugins.treesitter',
  require 'plugins.ui',
  require 'plugins.vim-sleuth',
  require 'plugins.which-key',
}
