[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[shell]
import = ["~/.config/alacritty/catppuccin/catppuccin-latte.yml"]

[shell.env]
TERM = "xterm-256color"
