import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[window]
startup_mode = "Maximized"
dynamic_title = true

[env]
TERM = "xterm-256color"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
